### PR TITLE
fix basestring for python 3

### PR DESCRIPTION
**Pull request by l0rb**
issue #77

### CODE REVIEW

**Comment by RayXY** [comment]
sorry I did not see this PR when making earlier comments in another PR. Can you please add six in requirements with this PR, then I will merge it. Thanks

**Comment by RayXY** [comment]
@l0rb can you please hold on adding commits for now, we are having some internal discussion on how to support 2/3 properly (e.g. six vs future)

**Comment by RayXY** [comment]
It appears future is the recommend way of doing Python 2/3 porting where only 2.7 support is needed, which is the case here.

Do you mind change your implementation to use future lib instead of six? Or I can do it in a new PR.

**Comment by l0rb** [comment]
I created new PR for this. https://github.com/blockchain/api-v1-client-python/pull/79

**Pull request closed without merging**
